Repository Omigost/Omigost, pull requests merged in 2019-03, with the labels that each got.

#81 Fix linter
  frontend/configs/webpack/common.js
  frontend/src/components/App.tsx
  frontend/src/components/pages/Dashboard/index.tsx
  frontend/src/components/pages/Loading/index.tsx
  frontend/src/components/pages/Login/index.tsx
  frontend/src/components/universal/Breadcrumbs/index.tsx
  frontend/src/components/universal/Button/index.tsx
  frontend/src/components/universal/ButtonPanel/index.tsx
  frontend/src/components/universal/Card/index.tsx
  frontend/src/components/universal/CardDescription/index.tsx
  frontend/src/components/universal/CardImage/index.tsx
  frontend/src/components/universal/CardTitle/index.tsx
  frontend/src/components/universal/Chart/ChartDataOptionsPanel.tsx
  frontend/src/components/universal/Chart/ChartTypeSwitchPanel.tsx
  frontend/src/components/universal/Chart/index.tsx
  frontend/src/components/universal/DashboardPanel/index.tsx
  frontend/src/components/universal/DataGrid/CellRenderer.tsx
  frontend/src/components/universal/DataGrid/FilterRenderer.tsx
  frontend/src/components/universal/DataGrid/index.tsx
  frontend/src/components/universal/DataProvider/index.tsx
  frontend/src/components/universal/Description/index.tsx
  frontend/src/components/universal/InteractiveGrid/index.tsx
  frontend/src/components/universal/InteractiveNestedGrid/index.tsx
  frontend/src/components/universal/Loading/index.tsx
  frontend/src/components/universal/LoadingPanel/index.tsx
  frontend/src/components/universal/LoginPanel/index.tsx
  frontend/src/components/universal/Logo/index.tsx
  frontend/src/components/universal/Meter/index.tsx
  frontend/src/components/universal/Page/FillPage.tsx
  frontend/src/components/universal/Page/SinglePage.tsx
  frontend/src/components/universal/Page/index.tsx
  frontend/src/components/universal/SearchableList/index.tsx
  frontend/src/components/universal/SideMenu/index.tsx
  frontend/src/components/universal/Text/index.tsx
  frontend/src/components/universal/TextBox/index.tsx
  frontend/src/components/universal/TextInput/index.tsx
  frontend/src/components/universal/TinyButtons/index.tsx
  frontend/src/components/universal/Tooltip/index.tsx
  frontend/src/components/universal/index.tsx
  frontend/src/index.tsx
  frontend/src/modules/DashboardView/index.tsx
  frontend/src/modules/ModulesProvider.tsx
  frontend/src/modules/SettingsView/index.tsx
  frontend/src/modules/SettingsView/src/Panel/index.tsx
  frontend/src/routes/index.tsx
  frontend/tslint.json
Labels: BLOCKER, fix, review wanted

#94 Fix frontend missing icons
  frontend/src/components/App.tsx
Labels: fix, review wanted

#84 Custom grid renderers
  frontend/src/components/universal/DataGrid/CellRenderer.tsx
  frontend/src/components/universal/DataGrid/index.tsx
  frontend/src/components/universal/DataProvider/DataTypePresets.ts
  frontend/src/components/universal/DataProvider/index.tsx
Labels: BLOCKER, review wanted

#87 Add grid sorting
  frontend/src/components/universal/DataGrid/index.tsx
Labels: do not merge yet, review wanted

#100 Extract theming from aggrid and plug into our theme
  frontend/.gitignore
  frontend/configs/webpack/common.js
  frontend/package.json
  frontend/src/components/universal/DataGrid/CellRenderer.tsx
  frontend/src/components/universal/DataGrid/index.tsx
  frontend/src/components/universal/DataGrid/theme/ag-theme-common.scss
  frontend/src/components/universal/DataGrid/theme/ag-theme-vars.scss
  frontend/src/components/universal/DataGrid/theme/ag-theme.scss
  frontend/src/components/universal/DataGrid/theme/index.scss
Labels: do not merge yet, low priority, review wanted

#101 Add ES6 dynamic imports
  frontend/.babelrc
  frontend/configs/jest.preprocessor.js
  frontend/configs/webpack/dev.js
  frontend/configs/webpack/prod.js
  frontend/package.json
  frontend/tsconfig.json
Labels: do not merge yet, enhancement, review wanted

#104 Add popover component
  frontend/package.json
  frontend/src/components/universal/Popover/index.scss
  frontend/src/components/universal/Popover/index.tsx
  frontend/src/components/universal/index.tsx
Labels: do not merge yet, review wanted

#111 Implement abstract tree for forms
  frontend/src/components/universal/Form/compositeNodes.tsx
  frontend/src/components/universal/Form/defaultParserConfig.tsx
  frontend/src/components/universal/Form/index.tsx
  frontend/src/components/universal/Form/renderers/ObjectDefault.tsx
  frontend/src/components/universal/Form/renderers/StringDefault.tsx
  frontend/src/components/universal/Form/schemaParser.tsx
  frontend/src/components/universal/Form/schemaTypes.tsx
  frontend/src/components/universal/Form/simpleNodes.tsx
Labels: enhancement, low priority

#113 AJV validation for forms
  frontend/src/components/universal/Form/compositeNodes.tsx
  frontend/src/components/universal/Form/defaultParserConfig.tsx
  frontend/src/components/universal/Form/index.tsx
  frontend/src/components/universal/Form/renderers/ObjectDefault.tsx
  frontend/src/components/universal/Form/renderers/StringDefault.tsx
  frontend/src/components/universal/Form/schemaParser.tsx
  frontend/src/components/universal/Form/schemaTypes.tsx
  frontend/src/components/universal/Form/simpleNodes.tsx
Labels: enhancement, low priority

#78 Fix React warnings
  frontend/src/components/universal/Breadcrumbs/index.tsx
  frontend/src/components/universal/Chart/index.tsx
  frontend/src/components/universal/InteractiveGrid/index.tsx
  frontend/src/components/universal/SearchableList/index.tsx
  frontend/src/components/universal/SideMenu/index.tsx
  frontend/src/components/universal/TinyButtons/index.tsx
Labels: fix, low priority

#119 Fixed budget creation
  server/src/main/java/com/omigost/server/aws/BudgetService.java
  server/src/main/java/com/omigost/server/aws/NewBudgetRequestBuilder.java
  server/src/main/java/com/omigost/server/model/BudgetDecorator.java
  server/src/main/java/com/omigost/server/rest/BudgetController.java
  server/src/main/java/com/omigost/server/rest/dto/BudgetCreateRequest.java
Labels: fix
